CREATE TABLE sales(
	id SERIAL PRIMARY KEY,
	"productId" INTEGER NOT NULL REFERENCES products(id),
	"userId" INTEGER NOT NULL REFERENCES users(id),
	amount INTEGER NOT NULL,
	adress TEXT NOT NULL,
	"createdAt" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
	status TEXT NOT NULL DEFAULT 'criada'
);